# Generated by Django 4.0.8 on 2024-01-27 08:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sido",
                    models.CharField(
                        blank=True, help_text="시도명", max_length=10, null=True
                    ),
                ),
                ("regional_code", models.CharField(help_text="지역 코드", max_length=6)),
                (
                    "sigungu",
                    models.CharField(
                        blank=True, help_text="시군구명", max_length=15, null=True
                    ),
                ),
                (
                    "ubmyundong",
                    models.CharField(
                        blank=True, help_text="읍면동", max_length=15, null=True
                    ),
                ),
                (
                    "dongri",
                    models.CharField(
                        blank=True, help_text="동리", max_length=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "region",
            },
        ),
    ]
