# Generated by Django 4.0.8 on 2024-02-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "total_deal_price",
                    models.PositiveIntegerField(
                        blank=True, help_text="지역 총 매매가", null=True
                    ),
                ),
                (
                    "total_jeonse_price",
                    models.PositiveIntegerField(
                        blank=True, help_text="지역 총 전세가", null=True
                    ),
                ),
                (
                    "total_deal_price_per_pyung",
                    models.CharField(
                        blank=True,
                        help_text="지역 총 평당 매매가",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "total_jeonse_price_per_pyung",
                    models.CharField(
                        blank=True,
                        help_text="지역 총 평당 전세가",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "average_deal_price",
                    models.CharField(
                        blank=True,
                        help_text="지역 평균 매매가",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "average_jeonse_price",
                    models.CharField(
                        blank=True,
                        help_text="지역 평균 전세가",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "average_deal_price_per_pyung",
                    models.CharField(
                        blank=True,
                        help_text="지역 전용면적 평균 매매 평당가",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "average_jeonse_price_per_pyung",
                    models.CharField(
                        blank=True,
                        help_text="지역 전용면적 평균 전세 평당가",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "deal_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="매매 개수", null=True
                    ),
                ),
                (
                    "jeonse_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="전세 개수", null=True
                    ),
                ),
                ("deal_date", models.DateField(help_text="거래 날짜(2020-01)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="region_prices",
                        to="real_estate.region",
                    ),
                ),
            ],
            options={
                "db_table": "region_price",
            },
        ),
    ]
