# Generated by Django 4.0.8 on 2024-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0002_regionprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="monthly_rent",
            field=models.IntegerField(blank=True, help_text="월세", null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="area_for_exclusive_use",
            field=models.CharField(
                help_text="전용면적(제곱미터)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="brokerage_type",
            field=models.CharField(
                blank=True,
                choices=[("BROKERAGE", "BROKERAGE"), ("DIRECT", "DIRECT")],
                help_text="중개/직거래(거래유형)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="is_deal_canceled",
            field=models.BooleanField(
                blank=True,
                help_text="해제여부(거래계약이 무효, 취소, 해제)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="land_area",
            field=models.CharField(
                blank=True, help_text="대지권면적", max_length=20, null=True
            ),
        ),
        migrations.DeleteModel(
            name="MonthlyRent",
        ),
    ]
