version: '3.7'
services:
  django:
    image: django
    container_name: django
    build:
      context: .
      dockerfile: dockerfile-development-window
    restart: always
    env_file: env/.env.development.window
    ports:
      - "8888:8888"
    command:
      - sh
      - -c
      - |
        envsubst < ./manticore/manticore.conf.template > ./manticore/manticore.conf
        gunicorn modu_property.wsgi:application --bind 0.0.0.0:8888 --workers 1 --threads 1
    volumes:
      - .:/modu_property/
      - /var/run/docker.sock:/var/run/docker.sock  # django container에서 manticore container에 indexer 실행하기 위해 설정함
    extra_hosts:
      - "host.docker.internal:host-gateway"

  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    environment:
      - EXTRA=1
    env_file: env/.env.development.window
    restart: always
    ports:
      - 127.0.0.1:9306:9306
      - 127.0.0.1:9308:9308
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
      - ./manticore/log:/var/log/manticore
      - ./manticore/index:/var/index/manticore
    depends_on:
      - django
    extra_hosts:
      - "host.docker.internal:host-gateway"


  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.development.window.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - "8080:8080"
    depends_on:
      - django
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_worker:
    container_name: celery_worker
    image: django
    restart: always
    volumes:
      - .:/var/www/modu_property/worker
    command:
      - sh
      - -c
      - celery -A modu_property worker -l INFO --concurrency 1 -E
      - tail -f /dev/null
    depends_on:
      - django
      - redis
    env_file: env/.env.development.window
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_beat:
    container_name: celery_beat
    image: django
    restart: always
    volumes:
      - .:/var/www/modu_property/beat
    command:
      - sh
      - -c
      - celery -A modu_property beat -l INFO
      - tail -f /dev/null
    depends_on:
      - django
      - redis
      - celery_worker
    env_file: env/.env.development.window
    extra_hosts:
      - "host.docker.internal:host-gateway"

  flower:
    container_name: celery_flower
    image: mher/flower
    env_file: env/.env.development.window
    ports:
      - 5555:5555
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - celery_beat

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"