version: '3.7'
services:
  django:
    container_name: django
    image: gidlemyeon/modu_property_platform_development:django
    build:
      context: .
      dockerfile: dockerfile-development
    restart: always
    env_file: env/.env.development
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        envsubst < ./manticore/manticore.conf.template > ./manticore/manticore.conf
        export SERVER_ENV=development
        gunicorn modu_property.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    volumes:
      - .:/modu_property
      - static_volume:/modu_property/static
       - /var/run/docker.sock:/var/run/docker.sock  # django container에서 manticore container에 indexer 실행하기 위해 설정함
    network_mode: "host"
    extra_hosts:
      - "nginx:127.0.0.1"

  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    environment:
      - EXTRA=1
    env_file: env/.env.development
    restart: always
    ports:
      - 127.0.0.1:9306:9306
      - 127.0.0.1:9308:9308
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
      - ./manticore/log:/var/log/manticore
      - ./manticore/index:/var/index/manticore
    depends_on:
      - django
    network_mode: "host"

  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.development.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/modu_property/static
    ports:
      - "80:80"
    depends_on:
      - django
    network_mode: "host"

  celery_worker:
    container_name: celery_worker
    image: gidlemyeon/modu_property_platform_development:django
    restart: always
    volumes:
      - .:/var/www/modu_property/worker
    command:
      - sh
      - -c
      - celery -A modu_property worker -l INFO --concurrency 1 -E
      - tail -f /dev/null
    depends_on:
      - django
      - redis
    env_file: env/.env.development
    network_mode: "host"

  celery_beat:
    container_name: celery_beat
    image: gidlemyeon/modu_property_platform_development:django
    volumes:
      - .:/var/www/modu_property/beat
    command:
      - sh
      - -c
      - celery -A modu_property beat -l INFO
      - tail -f /dev/null
    depends_on:
      - django
      - redis
      - celery_worker
    env_file: env/.env.development
    network_mode: "host"

  flower:
    container_name: celery_flower
    image: mher/flower
    env_file: env/.env.development
    ports:
      - 5555:5555
    depends_on:
      - celery_beat
    network_mode: "host"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    network_mode: "host"

volumes:
  static_volume:
