version: '3.7'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: jonasal/nginx-certbot:latest
    env_file:
      - .env.nginx.dev
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  web:
    container_name: core_app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env.dev
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        python manage.py migrate &&
        gunicorn modu_property.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
     - db
  celery:
    container_name: celery
    build:
      context: .
    restart: always
    volumes:
      - static_volume:/app/backend/django_static
    command:
      - sh
      - -c
      - celery -A modu_property worker -l INFO --concurrency 1 -E
    depends_on:
      - web
      - redis
  celery-beat:
    container_name: celery-beat
    build:
      context: .
    volumes:
      - static_volume:/app/backend/django_static
    command:
      - sh
      - -c
      - celery -A modu_property beat -l INFO
    depends_on:
      - web
      - redis
      - celery
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
  db:
    container_name: core_db
    image: postgres:14.6-alpine
    env_file: .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - "POSTGRES_DB=modu_property"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
 
volumes:
  static_volume:
  postgres_data:
  nginx_secrets:
