# syntax=docker/dockerfile:experimental

FROM python:3.10-slim as python-base

RUN apt-get update \
&& apt-get install default-mysql-client gdal-bin libgdal-dev docker.io gettext -yqq 

FROM python-base as poetry-base
WORKDIR /modu_property
COPY pyproject.toml pyproject.toml
RUN pip install poetry
RUN poetry export --without-hashes -f requirements.txt --output requirements.txt

FROM python-base as app
WORKDIR /modu_property
COPY . .
COPY --from=poetry-base /modu_property/requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt
