version: '3.7'
services:
  django:
    image: django
    container_name: django
    build:
      context: .
      dockerfile: ./dockerfile-local
    restart: always
    env_file: .env.local
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        envsubst < ./manticore/manticore.conf.template > ./manticore/manticore.conf
        python manage.py migrate &&
        gunicorn modu_property.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 1
    volumes:
      - .:/modu_property/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    environment:
      - EXTRA=1
    env_file: .env.local
    restart: always
    ports:
      - 127.0.0.1:9306:9306
      - 127.0.0.1:9308:9308
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
      - ./manticore/log:/var/log/manticore
      - ./manticore/index:/var/index/manticore
    depends_on:
      - django
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_worker:
    container_name: celery_worker
    image: django
    restart: always
    volumes:
      - .:/var/www/modu_property/worker
    command:
      - sh
      - -c
      - celery -A modu_property worker -l INFO --concurrency 1 -E
      - tail -f /dev/null
    depends_on:
      - django
      - redis_broker
    env_file: .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  celery_beat:
    container_name: celery_beat
    image: django
    volumes:
      - .:/var/www/modu_property/beat
    command:
      - sh
      - -c
      - celery -A modu_property beat -l INFO
      - tail -f /dev/null
    depends_on:
      - django
      - redis_broker
      - celery_worker
    env_file: .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"

  flower:
    container_name: celery_flower
    image: mher/flower
    env_file: .env.local
    ports:
      - 5555:5555
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - celery_beat

  redis_broker:
    container_name: redis_broker
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
