FROM python:3.9 as python-base

RUN apt-get update \
    && apt-get install gdal-bin libgdal-dev -y

FROM python-base as poetry-base

WORKDIR /modu_property

COPY pyproject.toml pyproject.toml

RUN pip install poetry

RUN poetry export --without-hashes -f requirements.txt --output requirements.txt

FROM python-base as app

# RUN apt-get update \
#     && apt-get install gdal-bin libgdal-dev -y

WORKDIR /modu_property

COPY --from=poetry-base /modu_property/requirements.txt .

RUN pip install -r /modu_property/requirements.txt

COPY . /modu_property
