version: '3.7'
services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile-testing
    restart: always
    env_file: .env.testing
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        export SERVER_ENV=testing
        gunicorn modu_property.wsgi --bind 0.0.0.0:8000 --workers 1 --threads 1
    volumes:
      - .:/modu_property
      - static_volume:/modu_property/static
    environment:
      - POSTGRES_DB=modu_property
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5432
    network_mode: "host"

volumes:
  static_volume:
