# Generated by Django 4.0.8 on 2023-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='기사 제목', max_length=100)),
                ('body', models.TextField(help_text='기사 본문')),
                ('published_date', models.DateTimeField(help_text='기사 게시일')),
                ('link', models.URLField(help_text='네이버 뉴스 플랫폼의 기사 링크')),
            ],
        ),
    ]
