# Generated by Django 4.0.8 on 2023-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_price', models.PositiveIntegerField(help_text='거래금액(거래금액(만원))')),
                ('deal_type', models.CharField(blank=True, choices=[('BROKERAGE_DEAL', '중개거래'), ('DIRECT_DEAL', '직거래')], help_text='중개/직거래(거래유형)', max_length=14, null=True)),
                ('build_year', models.SmallIntegerField(help_text='건축년도')),
                ('deal_year', models.SmallIntegerField(help_text='계약년도(년)')),
                ('land_area', models.CharField(help_text='대지권면적', max_length=10)),
                ('dong', models.CharField(help_text='동', max_length=10)),
                ('name', models.CharField(help_text='연립/다세대 이름', max_length=30)),
                ('deal_month', models.SmallIntegerField(help_text='계약 월')),
                ('deal_day', models.SmallIntegerField(help_text='계약 일')),
                ('area_for_exclusive_use', models.CharField(help_text='전용면적(제곱미터)', max_length=7)),
                ('lot_number', models.CharField(help_text='지번(구획마다 부여된 땅 번호, 서울특별시 서초구 반포동 1-1)', max_length=30)),
                ('regional_code', models.CharField(help_text='지역코드', max_length=5)),
                ('floor', models.CharField(help_text='층', max_length=2)),
                ('is_deal_canceled', models.BooleanField(help_text='해제여부(거래계약이 무효, 취소, 해제)')),
                ('deal_canceld_date', models.DateField(blank=True, help_text='해제사유 발생일', null=True)),
                ('broker_address', models.CharField(blank=True, help_text='중개업소 주소(중개사소재지)', max_length=30, null=True)),
                ('road_name_address', models.CharField(help_text='도로명 주소', max_length=30)),
                ('latitude', models.CharField(help_text='위도', max_length=10)),
                ('longitude', models.CharField(help_text='경도', max_length=10)),
                ('pyung', models.CharField(help_text='평', max_length=6)),
                ('price_per_pyung', models.CharField(help_text='평당가', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
