# Generated by Django 4.0.8 on 2023-11-04 13:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='부동산 이름', max_length=30, null=True)),
                ('build_year', models.SmallIntegerField(help_text='건축년도')),
                ('regional_code', models.CharField(help_text='지역코드', max_length=5)),
                ('lot_number', models.CharField(help_text='지번(구획마다 부여된 땅 번호, 서울특별시 서초구 반포동 1-1)', max_length=50)),
                ('road_name_address', models.CharField(help_text='도로명 주소', max_length=50)),
                ('latitude', models.CharField(help_text='위도', max_length=20)),
                ('longitude', models.CharField(help_text='경도', max_length=20)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'villa',
            },
        ),
        migrations.CreateModel(
            name='VillaDeal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deal_price', models.PositiveIntegerField(help_text='거래금액(거래금액(만원))')),
                ('deal_type', models.CharField(blank=True, choices=[('BROKERAGE_DEAL', '중개거래'), ('DIRECT_DEAL', '직거래')], help_text='중개/직거래(거래유형)', max_length=14, null=True)),
                ('deal_year', models.SmallIntegerField(help_text='계약년도(년)')),
                ('land_area', models.CharField(help_text='대지권면적', max_length=10)),
                ('deal_month', models.SmallIntegerField(help_text='계약 월')),
                ('deal_day', models.SmallIntegerField(help_text='계약 일')),
                ('area_for_exclusive_use', models.CharField(help_text='전용면적(제곱미터)', max_length=7)),
                ('floor', models.CharField(help_text='층', max_length=2)),
                ('is_deal_canceled', models.BooleanField(help_text='해제여부(거래계약이 무효, 취소, 해제)')),
                ('deal_canceld_date', models.DateField(blank=True, help_text='해제사유 발생일', null=True)),
                ('area_for_exclusive_use_pyung', models.CharField(help_text='전용면적(평)', max_length=6)),
                ('area_for_exclusive_use_price_per_pyung', models.CharField(help_text='전용면적 평당가', max_length=8)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='villa_deal', to='property.villa')),
            ],
            options={
                'db_table': 'villa_deal',
            },
        ),
    ]
