name: Django CI

on:
  pull_request:
    branches:
      - dev

env:
  SERVER_ENV: "dev"
  DEBUG: ${{secrets.DEBUG}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  DB_ENGINE: ${{secrets.DB_ENGINE}}
  DB_NAME: ${{secrets.DB_NAME}}
  USER: ${{secrets.USER}}
  PASSWORD: ${{secrets.PASSWORD}}
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}
  HOST: "db"
  PORT: "5432"
  CELERY_BROKER_URL: ${{secrets.CELERY_BROKER_URL}}
  LOG_LEVEL: ${{secrets.LOG_LEVEL}}
  NAVER_NEWS_API_CLIENT_ID: ${{secrets.NAVER_NEWS_API_CLIENT_ID}}
  NAVER_NEWS_API_CLIENT_SECRET: ${{secrets.NAVER_NEWS_API_CLIENT_SECRET}}
  DJANGO_ALLOWED_HOSTS: ${{secrets.DJANGO_ALLOWED_HOSTS}}

jobs:
  test_project:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: coredb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: psycopg2 prerequisites
        run: sudo apt-get install python3-capstone libpq-dev
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          pytest .
  deploy:
    name: Deploying
    needs: [ test_project ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application
        uses: appleboy/ssh-action@master
        with:
          host: dev.modu-property.com
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            cd ~/.scripts
            ./docker-deploy-dev.sh